services: 
  app: 
    image: tiny-py:slim
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
    depends_on: 
      - db

  db: 
    image: postgres:16
    environment: 
      - POSTGRES_USER=devusser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=appdb
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: 
